### ISSUE TITLE
Bug on respawn

### ISSUE THREAD

**Issue by stitchinger** [Adrakaris/spigot-spicyhearts#1]
Hello, I found a bug in your plugin. 
This is how to replicate it:
1. Die
2. Dont respawn, instead go to titlescreen.
3. Rejoin the server

Now you should land on the respawn-screen, but instead your player just lives again and stand there, where they previously died.

**Comment by Adrakaris** [comment]
Was to do with calling updateHealth and breaking the death loop - now on rejoin should see the death screen if dead already.
